[image]
# Path to the source image (all major formats).
# Relative paths are resolved from the script directory; absolute paths are allowed.
path = "img/fry.svg"

# Maximum luminance used when selecting pixels for drawing.
# Possible values: [0–255] (the less value, the darker a pixel must be to be drawn).
max_luminosity = 200


[canvas]
# Target drawing area on the device screen (in device pixels).
# x, y define the top-left corner; width, height define the size.
x = 300
y = 670
width = 650
height = 490


[swipe]
# Maximum number of pixels per swipe gesture segment.
# Longer strokes are split into multiple swipes to avoid OS gesture limits.
swipe_length = 200

# Delay between consecutive swipe points, in milliseconds.
# Lower values draw faster but may lead to missed touches.
swipe_duration = 1


[debug]
# Draw the target canvas bounding rectangle.
# Possible values: [true, false]
draw_canvas_rect = true

# Draw the image bounding rectangle (before fitting into the canvas).
# Possible values: [true, false]
draw_image_rect = true

# Draw the content bounding rectangle (tight bounds of black pixels).
# Possible values: [true, false]
draw_content_rect = true


[target_platform]
# Target platform for drawing.
# Possible values: ["android"]
# Other platforms can be implemented via Appium drivers: https://appium.io/docs/en/2.19/ecosystem/drivers/
# iOS is excluded: system gestures are blocked for apps signed with distribution certificates.
name = "android"
